"""Unit tests for the licence gate (tools/check_licenses.py).

Only the pure half: name normalisation, lock parsing with marker evaluation,
and the verdict/allowlist decision table. Nothing here runs pip-licenses or
touches a venv -- that part is I/O against whatever happens to be installed on
the machine, and a gate whose tests depend on that is a gate that goes red for
reasons nobody can reproduce.

Run:  cd tools; python -m pytest tests -q       (any interpreter with pytest)
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

check_licenses = pytest.importorskip("check_licenses")


def test_normalize_matches_pep503():
    assert check_licenses.normalize("pyobjc-framework-Cocoa") == "pyobjc-framework-cocoa"
    assert check_licenses.normalize("py_rust_stemmers") == "py-rust-stemmers"
    assert check_licenses.normalize("Zope.Interface") == "zope-interface"


def test_verdict_reports_the_most_specific_licence():
    # "GPL" is a substring of both; a plain-GPL verdict on an LGPL package would
    # send the reader to the wrong obligation entirely.
    assert check_licenses.verdict("GNU Lesser General Public License v3 (LGPLv3)") == "LGPL"
    assert check_licenses.verdict("GNU Affero General Public License v3") == "AGPL"
    assert check_licenses.verdict("GNU General Public License v2 (GPLv2)") == "GPL"
    assert check_licenses.verdict("Server Side Public License (SSPL)") == "SSPL"
    assert check_licenses.verdict("MIT License") == ""
    assert check_licenses.verdict("BSD-3-Clause") == ""
    # Spelled out, with no acronym anywhere in the string -- the hole an
    # acronym-only gate has, and the one that lets AGPL through (2026-08-17).
    assert check_licenses.verdict("GNU Lesser General Public License") == "LGPL"
    assert check_licenses.verdict("GNU Library General Public License") == "LGPL"
    assert check_licenses.verdict("GNU General Public License, version 3") == "GPL"
    assert check_licenses.verdict("Mozilla Public License 2.0 (MPL 2.0)") == ""


def test_verdict_treats_missing_metadata_as_unknown():
    for value in ("UNKNOWN", "", "   ", None):
        assert check_licenses.verdict(value) == "UNKNOWN"


def _lock(tmp_path: Path) -> Path:
    path = tmp_path / "requirements.lock"
    path.write_text(textwrap.dedent("""\
        # generated by uv
        colorama==0.4.6 ; sys_platform == 'win32' \\
            --hash=sha256:aaaa
        pyobjc-core==12.2.2 ; sys_platform == 'darwin' \\
            --hash=sha256:bbbb
        python-xlib==0.33 ; sys_platform == 'linux' \\
            --hash=sha256:cccc
        watchdog==6.0.0 \\
            --hash=sha256:dddd
        pyobjc-framework-Cocoa==12.2.2 ; sys_platform == 'darwin'
        """), encoding="utf-8")
    return path


def test_parse_lock_evaluates_markers_per_platform(tmp_path):
    """The whole reason markers matter: python-xlib is pystray's Linux backend
    and is LGPL. It is in the companion lock and is in no companion build."""
    lock = _lock(tmp_path)
    win = check_licenses.parse_lock(lock, "win32")
    mac = check_licenses.parse_lock(lock, "darwin")
    linux = check_licenses.parse_lock(lock, "linux")

    assert win == {"colorama", "watchdog"}
    assert mac == {"pyobjc-core", "pyobjc-framework-cocoa", "watchdog"}
    assert linux == {"python-xlib", "watchdog"}


def test_parse_lock_ignores_hash_lines_and_comments(tmp_path):
    lock = _lock(tmp_path)
    names = check_licenses.parse_lock(lock, "win32")
    assert not any(n.startswith("hash") or n.startswith("--") for n in names)


def test_parse_lock_normalises_names(tmp_path):
    lock = _lock(tmp_path)
    assert "pyobjc-framework-cocoa" in check_licenses.parse_lock(lock, "darwin")


def test_the_real_locks_exist_and_parse():
    """A missing or unparsable lock must not read as 'nothing to report'."""
    for target in check_licenses.TARGETS:
        assert target.lock.exists(), f"{target.lock} is missing -- regenerate it"
        for platform in target.platforms:
            names = check_licenses.parse_lock(target.lock, platform)
            assert names, f"{target.lock} parsed to zero packages on {platform}"


def test_allowlist_entries_all_carry_a_reason():
    """The gate enforces this per finding; this catches an entry added for a
    package that is not currently tripping it, which the gate would not see."""
    allow = check_licenses.load_allowlist(check_licenses.ALLOWLIST_PATH)
    assert allow, "tools/license_allowlist.toml has no [allow.*] entries"
    for name, entry in allow.items():
        assert entry.get("reason", "").strip(), f"{name}: allowlist entry has no reason"
        assert entry.get("license", "").strip(), f"{name}: allowlist entry has no license"


def _fake_target(label: str, lock: Path, platforms: list[str]) -> "check_licenses.Target":
    # venvs=[] rather than a real path: scan_venvs() must not touch anything on
    # disk for these tests (module docstring) -- an empty list of venvs skips
    # straight to "every wanted package is UNSCANNED", which is exactly the
    # shape --only/--platform need to prove without pip-licenses or a venv.
    return check_licenses.Target(label=label, lock=lock, platforms=platforms,
                                 venvs=[], why="test fixture")


def test_only_skips_targets_entirely(tmp_path, monkeypatch):
    """A target excluded by --only must not even have its lock existence
    checked -- that is what lets the Linux job ask only for dashboard-container
    without a warning about companion/requirements.lock, which it never
    installed and has no reason to open."""
    lock_a = _lock(tmp_path)
    missing_lock_b = tmp_path / "does-not-exist.lock"
    targets = [
        _fake_target("a", lock_a, ["win32"]),
        _fake_target("b", missing_lock_b, ["win32"]),
    ]
    monkeypatch.setattr(check_licenses, "TARGETS", targets)

    findings, warnings = check_licenses.check(only=["a"])

    assert all(f.target == "a" for f in findings)
    assert not any("b" in w and "does not exist" in w for w in warnings)


def test_platform_restricts_which_packages_a_target_needs(tmp_path, monkeypatch):
    """companion's lock feeds both a win32 and a darwin build; a single CI job
    can only ever install one of those. --platform is what lets the Windows
    job assert colorama/watchdog without also demanding pyobjc, which no
    Windows venv can ever contain."""
    lock = _lock(tmp_path)
    target = _fake_target("companion", lock, ["win32", "darwin"])
    monkeypatch.setattr(check_licenses, "TARGETS", [target])

    findings, _ = check_licenses.check(platforms=["win32"])
    packages = {f.package for f in findings}
    assert packages == {"colorama", "watchdog"}

    # The SAME Target instance, deliberately (bug-hunt-2026-09-03
    # server-tools-4): check() used to accumulate the names it considered onto
    # the module-level Target and never reset them, so a second call in one
    # process reported the first call's platform slice (colorama here) as
    # UNSCANNED, which --strict turns into a FAIL for a package this slice
    # never asked about.
    findings, _ = check_licenses.check(platforms=["darwin"])
    packages = {f.package for f in findings}
    assert packages == {"pyobjc-core", "pyobjc-framework-cocoa", "watchdog"}
    assert "colorama" not in packages


def test_platform_with_no_overlap_warns_instead_of_silently_passing(tmp_path, monkeypatch):
    """Asking for a platform a target does not ship on at all (e.g. `--platform
    linux` against companion) must not look identical to 'checked, found
    nothing wrong' -- that is a misconfigured CI step, not a clean target."""
    lock = _lock(tmp_path)
    target = _fake_target("companion", lock, ["win32", "darwin"])
    monkeypatch.setattr(check_licenses, "TARGETS", [target])

    findings, warnings = check_licenses.check(platforms=["linux"])
    assert findings == []
    assert any("nothing checked" in w for w in warnings)


def test_pystray_is_gone_and_stays_gone():
    """COMMERCIAL_READINESS.md item 3, verified 2026-08-17.

    pystray was LGPLv3 statically linked into the single-file PyInstaller
    freeze -- the ranked stop-ship. The tray is `tray_native.py` now (ctypes on
    Windows, PyObjC on macOS) and pystray is out of pyproject.toml, so it is out
    of the lock on every platform. There is deliberately NO allowlist entry: if
    it returns as a declared dependency the gate fails, which is the whole
    reason the entry was deleted rather than kept "just in case".

    `tray.py`'s CCSYNC_TRAY_BACKEND=pystray escape hatch is for a developer who
    installs it by hand and refuses to load in a frozen build -- that is a
    hand-installed package in a developer's venv, not a conveyed one, and it is
    correctly invisible to a gate that reads the lock.
    """
    companion = next(t for t in check_licenses.TARGETS if t.label == "companion")
    for platform in ("win32", "darwin", "linux"):
        assert "pystray" not in check_licenses.parse_lock(companion.lock, platform), (
            f"pystray is back in companion/requirements.lock on {platform} -- it is "
            f"LGPLv3 and the companion is a single-file freeze (item 3)")

    allow = check_licenses.load_allowlist(check_licenses.ALLOWLIST_PATH)
    assert "pystray" not in allow, (
        "the pystray allowlist entry outlived the dependency -- delete it, or "
        "the gate will wave it through if it ever comes back")
